# -*- coding: utf-8 -*-
"""instagram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Id3DX1Bdlb8wpE9a9EBs5E4vYjS8Wuay
"""

from selenium import webdriver
from time import sleep
from selenium.webdriver.common.keys import Keys
from random import randint

class Bot():

    links = []

    comments = [
        'Great post!', 'Awesome!'
    ]

    def _init_(self):
        self.login('id','pass')
        self.like_comment_by_hashtag('likes')

    def login(self, username, password):
        self.driver = webdriver.Chrome(executable_path='C:/Users/Ritika/AppData/Local/chromedriver.exe')
        self.driver.get('https://instagram.com/')
        sleep(5)
        username_input = self.driver.find_element_by_xpath('//*[@id="loginForm"]/div/div[1]/div/label/input')
        username_input.send_keys(username)
        sleep(1)
        password_input = self.driver.find_element_by_xpath('//*[@id="loginForm"]/div/div[2]/div/label/input')
        password_input.send_keys(password)
        sleep(1)
        self.driver.find_element_by_xpath('//*[@id="loginForm"]/div/div[3]/button').click()
        sleep(5)
        self.driver.find_element_by_xpath("//button[contains(text(), 'Not Now')]").click() 
        sleep(5)
        self.driver.find_element_by_xpath("//button[contains(text(), 'Not Now')]").click() 

    def like_comment_by_hashtag(self, hashtag):
        self.driver.get('https://www.instagram.com/explore/tags/{}/'.format(hashtag))
        links = self.driver.find_elements_by_tag_name('a')

        def condition(link):
            return '.com/p/' in link.get_attribute('href')
        valid_links = list(filter(condition, links))

        for i in range(5):
            link = valid_links[i].get_attribute('href')
            if link not in self.links:
                self.links.append(link)

        for link in self.links:
            self.driver.get(link)
            # like
            sleep(8)
            self.driver.find_element_by_xpath("//span[@class='fr66n']").click()
            sleep(5)
            #self.driver.find_element_by_xpath("//span[@class='wmtNn']").click()

            # comment
            self.driver.find_element_by_class_name('RxpZH').click() 
            sleep(1)
            self.driver.find_element_by_xpath("//textarea[@placeholder='Add a comment…']").send_keys(self.comments[randint(0,1)])
            sleep(1)
            self.driver.find_element_by_xpath("//button[@type='submit']").click()
            
            #save
            sleep(8)
            self.driver.find_element_by_xpath("//span[@class='wmtNn']").click()

def main():
    while True:
        my_bot = Bot()
        sleep(5*60) # one hour

if _name_ == '_main_':
    main()